<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context.xsd">       
<context:annotation-config/>
<context:component-scan base-package="com.nisum.DemoExceptionHandling"/>    

<bean class="org.springframework.jdbc.datasource.DriverManagerDataSource" id="dataSource">
   <property name="driverClassName" value="com.mysql.jdbc.Driver"></property>
   <property name="url" value="jdbc:mysql://localhost:3306/db"></property>
   <property name="username" value="root"></property>
   <property name="password" value="12345"></property>
</bean>

<bean id = "employeeDaoImpl" class = "com.nisum.DemoExceptionHandling.EmployeeDaoImpl">
      <property name = "dataSource" ref = "dataSource" />    
   </bean>

 
<!-- <bean id="employeeDaoImpl" class="com.nisum.dataAccess.EmployeeDaoImpl"></bean> -->

<bean id="employeeService" class="com.nisum.DemoExceptionHandling.EmployeeService">
	<property name="employeeDaoImpl" ref="employeeDaoImpl"></property>
</bean>





</beans>